project_id = "qlcuwqkeqfawwezhqjei"

[functions.ai-chat]
enabled = true
verify_jwt = false

[functions.ai-describe-image]
enabled = true
verify_jwt = false

[functions.ai-generate-image]
enabled = true
verify_jwt = false

[functions.ai-suggest]
enabled = true
verify_jwt = false
